import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.routes.js";
import usersRouter from "./users.routes.js";
import userRouter from "./user.routes.js";
import serversRouter from "./servers.routes.js";
import vpnRouter from "./vpn.routes.js";
import vouchersRouter from "./vouchers.routes.js";
import plansRouter from "./plans.routes.js";
import inboundsRouter from "./inbounds.routes.js";
import usageRouter from "./usage.routes.js";
import resellersRouter from "./resellers.routes.js";
import licensesRouter from "./licenses.routes.js";
import adminRouter from "./admin.routes.js";
import apiKeysRouter from "./api-keys.routes.js";
import auditRouter from "./audit.routes.js";
import notificationsRouter from "./notifications.routes.js";
import settingsRouter from "./settings.routes.js";
import vpnProfilesRouter from "./vpn-profiles.routes.js";
import vpnTemplatesRouter from "./vpn-templates.routes.js";
import ticketsRouter from "./tickets.routes.js";
import mobileRouter from "./mobile.routes.js";
import paymentsRouter from "./payments.routes.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth",           authRouter);
router.use("/users",          usersRouter);
router.use("/user",           userRouter);
router.use("/servers",        serversRouter);
router.use("/vpn",            vpnRouter);
router.use("/vpn-profiles",   vpnProfilesRouter);
router.use("/vpn-templates",  vpnTemplatesRouter);
router.use("/vouchers",       vouchersRouter);
router.use("/plans",          plansRouter);
router.use("/inbounds",       inboundsRouter);
router.use("/usage",          usageRouter);
router.use("/resellers",      resellersRouter);
router.use("/licenses",       licensesRouter);
router.use("/admin",          adminRouter);
router.use("/api-keys",       apiKeysRouter);
router.use("/audit",          auditRouter);
router.use("/notifications",  notificationsRouter);
router.use("/settings",       settingsRouter);
router.use("/tickets",        ticketsRouter);
router.use("/payments",       paymentsRouter);

export default router;
